#!/bin/sh

# monitor event0 keys and send a raw hexcode to home assistant webhook
MYEVDEV="/dev/input/event0"
WH="87161aac-f0ae-4939-8ad3-4f36b6482bb9"
HA="homeassistant.local"
HP=8123

# unused: cuts the squeezebox playername from squeezeplay cfg:
#SB="$(grep name= /etc/squeezeplay/userpath/settings/Playback.lua  | awk -F'name="' '{print $2}' | cut -d'"' -f1)"

while true; do
    KEYVAL="$(hexdump "$MYEVDEV" -n 12 | awk '{print $7}')"
    if [ -n "$KEYVAL" ]; then
      wget --post-data "key=$KEYVAL" http://$HA:$HP/api/webhook/$WH -q -O-
    fi
done
